version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - echo Entered the install phase...
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - apt-get update && apt-get -y install jq python3-pip python3-dev maven curl && pip3 install --upgrade awscli
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region eu-central-1)
      - curl -L https://git.io/get_helm.sh | bash
      - helm init --client-only
      - helm plugin install https://github.com/hypnoglow/helm-s3.git
      - helm s3 init s3://samply-helm-charts/charts
      - helm repo add samply-charts s3://samply-helm-charts/charts
      - export VERSION=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo $VERSION
  build:
    commands:
      - mvn -B clean package
      - docker build -f api/src/main/docker/Dockerfile.jvm -t catalog-api:${VERSION} ./api
      - docker images
      - docker tag catalog-api:${VERSION} ${IMAGE_REPO_HOST}/samply/catalog-api:${VERSION}
      - docker tag catalog-api:${VERSION} ${IMAGE_REPO_HOST}/samply/catalog-api:latest
      - docker images
      - helm package ./helm/catalog-api --app-version ${VERSION}
  post_build:
    commands:
      - echo push latest Docker images to ECR...
      - docker push ${IMAGE_REPO_HOST}/samply/catalog-api:${VERSION}
      - docker push ${IMAGE_REPO_HOST}/samply/catalog-api
      - helm s3 push --force ./catalog-api-0.0.1.tgz samply-charts