version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - echo Entered the install phase...
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - apt-get update -y
      - apt-get install -y maven
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region eu-central-1)
  build:
    commands:
      - mvn -B clean package
      - cd api
      - docker build -f src/main/docker/Dockerfile.jvm -t catalog-api:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/samply/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo push latest Docker images to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/samply/$IMAGE_REPO_NAME:$IMAGE_TAG