openapi: 3.0.0
info:
  title: "Catalog API"
  version: "1.0.0"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
    oauth2:
      type: oauth2
      flows:
        password:
          tokenUrl: http://localhost:8090/auth/realms/samply-istio/protocol/openid-connect/token

security:
  - oauth2: []